# Generated by Django 4.2.30 on 2026-06-06 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('pullup_bar', 'Pull-up Bar'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell + Plates'), ('bands', 'Resistance Bands'), ('rowing_machine', 'Rowing Machine'), ('bench', 'Bench'), ('kettlebell', 'Kettlebell'), ('rings', 'Gymnastic Rings')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_loadable', models.BooleanField(default=False)),
                ('load_unit', models.CharField(choices=[('none', 'None'), ('kg', 'Kilograms'), ('lb', 'Pounds'), ('band_level', 'Band Level')], default='none', max_length=16)),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('difficulty_rank', models.PositiveIntegerField(help_text="Order within the pattern's ladder; lower = easier.")),
                ('progression_mode', models.CharField(choices=[('difficulty', 'Difficulty (climb the ladder)'), ('load', 'Load (add weight/band level)')], default='difficulty', max_length=16)),
                ('rep_range_min', models.PositiveIntegerField(default=5)),
                ('rep_range_max', models.PositiveIntegerField(default=12)),
                ('is_timed', models.BooleanField(default=False, help_text='True for holds (planks); values are seconds.')),
                ('video_url', models.URLField(blank=True, default='')),
                ('cues', models.TextField(blank=True, default='')),
                ('placement_threshold', models.PositiveIntegerField(default=0, help_text='Min AMRAP reps/seconds to be placed on this rung.')),
            ],
            options={
                'ordering': ['pattern', 'difficulty_rank'],
            },
        ),
        migrations.CreateModel(
            name='MovementPattern',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('horizontal_push', 'Horizontal Push'), ('vertical_pull', 'Vertical Pull'), ('vertical_push', 'Vertical Push'), ('lower_unilateral', 'Lower (Unilateral)'), ('core_anti_extension', 'Core (Anti-Extension)'), ('hinge', 'Hinge / Posterior Chain')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('primary_muscles', models.CharField(blank=True, default='', max_length=200)),
                ('is_lower_body', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrescribedExercise',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('target_reps_min', models.PositiveIntegerField(default=5)),
                ('target_reps_max', models.PositiveIntegerField(default=12)),
                ('target_load', models.FloatField(blank=True, help_text='Load for load-mode exercises; null for bodyweight.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sessions_at_top', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('split', models.CharField(choices=[('full_body_3x', 'Full Body ×3/week'), ('upper_lower_4x', 'Upper/Lower ×4/week')], default='full_body_3x', max_length=24)),
                ('weekly_volume_target', models.PositiveIntegerField(default=8, help_text='Target working sets per pattern per week.')),
                ('source_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='the_cauldron.assessmentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_index', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=80)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='the_cauldron.program')),
            ],
            options={
                'ordering': ['program', 'day_index'],
                'unique_together': {('program', 'day_index')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=16)),
                ('program_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='the_cauldron.programday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEquipmentProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dumbbell_weights', models.JSONField(blank=True, default=list, help_text='Available dumbbell weights, e.g. [5,10,15].')),
                ('band_levels', models.JSONField(blank=True, default=list, help_text='Ordered band tensions/labels, easiest first.')),
                ('barbell_min_increment', models.FloatField(default=2.5)),
                ('barbell_plates', models.JSONField(blank=True, default=list)),
                ('load_unit', models.CharField(choices=[('none', 'None'), ('kg', 'Kilograms'), ('lb', 'Pounds'), ('band_level', 'Band Level')], default='kg', max_length=16)),
                ('equipment', models.ManyToManyField(blank=True, related_name='owners', to='the_cauldron.equipment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forge_equipment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_index', models.PositiveIntegerField()),
                ('expected_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_load', models.FloatField(blank=True, null=True)),
                ('actual_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_load', models.FloatField(blank=True, null=True)),
                ('is_amrap', models.BooleanField(default=False)),
                ('rir', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='the_cauldron.exercise')),
                ('prescribed_exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_logs', to='the_cauldron.prescribedexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='the_cauldron.workoutsession')),
            ],
            options={
                'ordering': ['session', 'prescribed_exercise', 'set_index'],
            },
        ),
        migrations.AddField(
            model_name='prescribedexercise',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='the_cauldron.programday'),
        ),
        migrations.AddField(
            model_name='prescribedexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='the_cauldron.exercise'),
        ),
        migrations.AddField(
            model_name='prescribedexercise',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='the_cauldron.movementpattern'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='the_cauldron.movementpattern'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='progression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='easier_variants', to='the_cauldron.exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='regression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harder_variants', to='the_cauldron.exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='required_equipment',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='the_cauldron.equipment'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('pattern', 'name')},
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reps_or_seconds', models.PositiveIntegerField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_cauldron.movementpattern')),
                ('placed_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='the_cauldron.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='the_cauldron.assessmentsession')),
                ('tested_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='the_cauldron.exercise')),
            ],
            options={
                'unique_together': {('session', 'pattern')},
            },
        ),
    ]
