# Generated by Django 4.2.30 on 2026-06-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_assessment_anchor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='prescribedexercise',
            name='target_rest_seconds',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
