# Generated by Django 4.2.30 on 2026-06-06 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0003_blockedexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='left_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='right_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescribedexercise',
            name='pending_progression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='the_cauldron.exercise'),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=12),
        ),
    ]
