# Generated by Django 4.2.30 on 2026-06-19 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0004_assessmentresult_left_reps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('region', models.CharField(choices=[('front', 'Front'), ('back', 'Back')], default='front', max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(blank=True, help_text='Muscles this movement trains; drives the exercise detail list and the daily worked-muscle diagram.', related_name='exercises', to='the_cauldron.muscle'),
        ),
    ]
