# Generated by Django 4.2.30 on 2026-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0005_muscle_exercise_muscles'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlog',
            name='left_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='right_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
