# Generated by Django 4.2.30 on 2026-07-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0007_reduce_rest_seconds_30pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='grip',
            field=models.CharField(choices=[('overhand', 'Overhand (pull-up)'), ('underhand', 'Underhand (chin-up)'), ('n/a', 'Not applicable')], default='n/a', max_length=12),
        ),
    ]
