# Generated by Django 4.2.30 on 2026-07-30 05:30

from django.db import migrations, models


def backfill_configured_at(apps, schema_editor):
    """Mark existing profiles as configured so they aren't sent back to setup.

    A profile predating this field counts as configured when the user has
    actually used the Forge — they picked gear, or they already have a program.
    """
    UserEquipmentProfile = apps.get_model('the_cauldron', 'UserEquipmentProfile')
    Program = apps.get_model('the_cauldron', 'Program')
    with_program = set(Program.objects.values_list('user_id', flat=True))
    for profile in UserEquipmentProfile.objects.all():
        if profile.equipment.exists() or profile.user_id in with_program:
            profile.configured_at = profile.updated_at
            profile.save(update_fields=['configured_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0009_exercise_is_per_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='userequipmentprofile',
            name='configured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_configured_at, migrations.RunPython.noop),
    ]
