# Generated by Django 4.2.30 on 2026-08-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0010_userequipmentprofile_configured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userequipmentprofile',
            name='bar_weight',
            field=models.FloatField(default=20.0, help_text='Weight of the empty bar.'),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='dumbbell_handle_weight',
            field=models.FloatField(default=2.0, help_text='Weight of one empty adjustable dumbbell handle.'),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='dumbbell_mode',
            field=models.CharField(choices=[('fixed', 'Fixed weights'), ('plates', 'Plate-loaded')], default='fixed', max_length=8),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='dumbbell_plates',
            field=models.JSONField(blank=True, default=list, help_text='Adjustable-dumbbell plates, e.g. [{"weight": 2.5, "count": 8}].'),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='kettlebell_handle_weight',
            field=models.FloatField(default=6.0, help_text='Weight of the empty adjustable kettlebell shell.'),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='kettlebell_mode',
            field=models.CharField(choices=[('fixed', 'Fixed weights'), ('plates', 'Plate-loaded')], default='fixed', max_length=8),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='kettlebell_plates',
            field=models.JSONField(blank=True, default=list, help_text='Adjustable-kettlebell plates, e.g. [{"weight": 2, "count": 6}].'),
        ),
        migrations.AddField(
            model_name='userequipmentprofile',
            name='kettlebell_weights',
            field=models.JSONField(blank=True, default=list, help_text='Fixed kettlebell weights, e.g. [12,16,24].'),
        ),
        migrations.AlterField(
            model_name='userequipmentprofile',
            name='barbell_min_increment',
            field=models.FloatField(default=2.5, help_text='Fallback step used only when no barbell plates are entered.'),
        ),
        migrations.AlterField(
            model_name='userequipmentprofile',
            name='barbell_plates',
            field=models.JSONField(blank=True, default=list, help_text='Barbell plates, e.g. [{"weight": 20, "count": 4}].'),
        ),
    ]
