# Generated by Django 4.2.30 on 2026-09-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0015_ab_wheel_and_drop_rowing_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='asymmetry_pct',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='left_reps',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='right_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='measures_asymmetry',
        ),
        migrations.RemoveField(
            model_name='setlog',
            name='left_reps',
        ),
        migrations.RemoveField(
            model_name='setlog',
            name='right_reps',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='key',
            field=models.CharField(choices=[('bodyweight', 'Bodyweight'), ('pullup_bar', 'Pull-up Bar'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell + Plates'), ('bands', 'Resistance Bands'), ('bench', 'Bench'), ('kettlebell', 'Kettlebell'), ('rings', 'Gymnastic Rings'), ('ab_wheel', 'Ab Wheel')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_per_side',
            field=models.BooleanField(default=False, help_text='True for movements performed one side at a time; rep targets are forced even.'),
        ),
    ]
