# Generated by Django 4.2.30 on 2026-09-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_cauldron', '0017_repair_zero_loads'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='alternative_equipment',
            field=models.ManyToManyField(blank=True, help_text='User needs at least one of these (in addition to all of required_equipment). Empty = no alternatives constraint.', related_name='alternative_exercises', to='the_cauldron.equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='variant_group',
            field=models.CharField(blank=True, default='', help_text='Slug shared by rungs that occupy the same ladder position.', max_length=32),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='key',
            field=models.CharField(choices=[('bodyweight', 'Bodyweight'), ('pullup_bar', 'Pull-up Bar'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell + Plates'), ('bands', 'Resistance Bands'), ('bench', 'Bench'), ('kettlebell', 'Kettlebell'), ('rings', 'Gymnastic Rings'), ('ab_wheel', 'Ab Wheel'), ('fat_grips', 'Fat Grips')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='movementpattern',
            name='key',
            field=models.CharField(choices=[('horizontal_push', 'Horizontal Push'), ('vertical_pull', 'Vertical Pull'), ('vertical_push', 'Vertical Push'), ('lower_unilateral', 'Lower (Unilateral)'), ('core_anti_extension', 'Core (Anti-Extension)'), ('hinge', 'Hinge / Posterior Chain'), ('grip', 'Grip / Forearms')], max_length=32, unique=True),
        ),
    ]
